services:
  harbor:
    container_name: harbor
    image: ghcr.io/bryanvanwinnendael/harbor:latest
    ports:
      - "8004:3000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock